### PR TITLE
esp32c3: collect dma channel

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
cc @jessebraham

**Comment by jessebraham** [comment]
I think these changes are probably technically fine, however I'm a little worried about how much work will be required to update `esp-hal` if we merge this. I don't want to get our PACs to a state where we're blocked from using the latest versions in the HAL due to something like this.

Have you looked into what's involved to reflect these changes in the HAL by any chance? Would be you able/willing to submit a PR to the HAL taking care of these changes?

(cc @bjoernQ, since he largely wrote the DMA driver in the HAL)

**Comment by burrbull** [comment]
For me this was first of all a good playground to improve `svdtools` :).
Anyway I'll look at the `hal` when have time. I think the should be 2 steps:
1 - porting (just replace access to register on ch(n).regname() instead of regname_ch(n)).
2 - work with channel as code unit. Although there could be some issues due to issues across family.
Also I need to check field names (and compare them across chips) as many of them can still have channel number in name. So a draft for now.

**Comment by burrbull** [comment]
Ready. Only blocked on `svdtools` release.

**Comment by burrbull** [comment]
cc @jessebraham
https://github.com/esp-rs/esp-hal/pull/1330

**Review by jessebraham — APPROVED** [review]
LGTM, thank you for this, and for updating the HAL as well!

**Pull request merged**
