### PR TITLE
Fix a typo (describtion -> description)

### PR DESCRIPTION
**Pull request by manio**

### CODE REVIEW

**Comment by jessebraham** [comment]
Thank you for the PR.

To make upstreaming changes to the official SVDs easier, we patch the SVDs in this repository rather than modifying them directly. It's too easy to miss changes and have regressions otherwise. Please refer to the [Getting Started](https://github.com/esp-rs/esp-pacs/#getting-started) section of the `README` for more information on how to make contributions to this repository.

**Comment by manio** [comment]
Yeah I was just reading the guide before, but I was hoping that single `sed` on the whole repository will make it work (as not only the source but also generated files are changed this way).

Sorry - I am not familiar with this tools like svdtools, xtask, pacs, etc.
So in this case I am ok if just close this PR - as I don't have spare time to take a deep look into this.

**Comment by manio** [comment]
Sorry - I don't know how it works. I read the whole guide, invoke the xtask via
`cargo run -- generate esp32`
and also
`cargo run -- patch`
But my working directory is still clean. Nothing is generated to commit. I also tried to do it with *after*
`git reset --soft` (from my commit)

**Comment by jessebraham** [comment]
Sorry, I had missed your comments somehow. Too many notifications 😁 

I have taken care of making these changes in #172, so thank you for bringing this to my attention!

**Pull request closed without merging**
