### PR TITLE
generate SVD-YAML

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by MabezDev** [comment]
cc @jessebraham @bjoernQ based on a discussion in matrix, @burrbull suggested adding a yaml representation of the svd for easier review.

I don't think I would personally use this, I tend to look at the cargo doc output instead, but I'd be interested to hear your points of view.

**Comment by burrbull** [comment]
An alternative (for review only) is to use @adamgreig `mmaps`. They are even more compact. Although they don't support enums.
See https://github.com/stm32-rs/stm32-rs-mmaps/

**Comment by jessebraham** [comment]
> I don't think I would personally use this, I tend to look at the cargo doc output instead, but I'd be interested to hear your points of view.

Yeah probably the same here, I've reviewed the majority of PRs in this repo and don't really feel any need to change my approach at this time.

**Comment by MabezDev** [comment]
Ah! I also completely forgot about the `html` xtask - that's really useful. @burrbull What do you think about the HTML viewer, we could check those in with each pr?

To try them:

1. cd in xtask
2. run `cargo run -- html`
3. Open one of the `$CHIP.html` in a browser

**Comment by burrbull** [comment]
Yeah. I know about `html`. I just thought about online review.
Closing for now.

**Pull request closed without merging**
