### PR TITLE
fix typo in efuse.rs

### PR DESCRIPTION
**Pull request by kons-9**
I fixed typo that I found in efuse.rs

### CODE REVIEW

**Comment by jessebraham** [comment]
Thanks for the PR.

Since we frequently regenerate the source files, we use patching to make modifications rather than editing source files directly. See the [Patching the SVDs](https://github.com/esp-rs/esp-pacs#patching-the-svds) section of the README for more details.

**Comment by kons-9** [comment]
I didn't see them, sorry.
So, What I should do is to add the patch in https://github.com/esp-rs/esp-pacs/blob/main/esp32c3/svd/patches/esp32c3.yaml, according to svdtools format, right?

**Comment by jessebraham** [comment]
> I didn't see them, sorry.

Not a problem, now you know! 😁 

> So, What I should do is to add the patch in https://github.com/esp-rs/esp-pacs/blob/main/esp32c3/svd/patches/esp32c3.yaml, according to svdtools format, right?

Yes that is correct! The [patching format specification](https://github.com/stm32-rs/svdtools#device-and-peripheral-yaml-format) should contain all the information you need, I hope.

**Comment by kons-9** [comment]
Please check it! is this ok?

**Comment by jessebraham** [comment]
Your patches look good, but that SVD should not have been included. Not sure what's going on there, the `.gitignore` should have covered that 😅 Also looks like not all re-generated sources files are included.

If you remove the SVD which you had previously committed, and then from within the `xtask/` directory run the command `cargo run -- generate esp32c3` you should be in good shape, I think. Doing this locally resulted in the following modified files, all of which should be included in this PR along with the YAML patches:

- `esp32c3/src/efuse.rs`
- `esp32c3/src/efuse/clk.rs`
- `esp32c3/src/efuse/conf.rs`
- `esp32c3/src/efuse/wr_tim_conf1.rs`
- `esp32c3/src/efuse/wr_tim_conf2.rs`
- `esp32c3/src/system.rs`
- `esp32c3/src/system/edma_ctrl.rs`

I'm sorry that this process was not more clear. In the meantime I have updated the repository's README which I hope makes things more clear now. If you have any feedback on that I'd love to hear it.

**Comment by kons-9** [comment]
I’m sorry but I misunderstood that I should use svdtools directly when I generate svd patch file. This is the reason that my commit contained svd file because svdtools generate *.svd.base.patched, which is not covered in .gitignore.
Now the process is also so clear, Thank you so much!
Anyway, I added all my files!

**Review by jessebraham — APPROVED** [review]
No apologies required, things were not clear before but hopefully now they are 😁 Thanks for your patience and for fixing this, LGTM!

**Pull request merged**
